# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/williams/MYFPGA/FSO FPGA/sfp_int/sfp_int_0/gt_ex/gt_ex.srcs/sources_1/ip/bram_rs/bram_rs.xci
# IP: The module: 'bram_rs' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/williams/MYFPGA/FSO FPGA/sfp_int/sfp_int_0/gt_ex/gt_ex.gen/sources_1/ip/bram_rs/bram_rs_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_rs'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/williams/MYFPGA/FSO FPGA/sfp_int/sfp_int_0/gt_ex/gt_ex.srcs/sources_1/ip/bram_rs/bram_rs.xci
# IP: The module: 'bram_rs' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/williams/MYFPGA/FSO FPGA/sfp_int/sfp_int_0/gt_ex/gt_ex.gen/sources_1/ip/bram_rs/bram_rs_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_rs'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
