# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/williams/MYFPGA/FPGA Training Data Etri_fso/sfp_int/sfp_int_0/gt_ex/gt_ex.srcs/sources_1/ip/gt/gt.xci
# IP: The module: 'gt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/williams/MYFPGA/FPGA Training Data Etri_fso/sfp_int/sfp_int_0/gt_ex/gt_ex.gen/sources_1/ip/gt/synth/gt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gt'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/williams/MYFPGA/FPGA Training Data Etri_fso/sfp_int/sfp_int_0/gt_ex/gt_ex.gen/sources_1/ip/gt/synth/gt.xdc
# XDC: The top module name and the constraint reference have the same name: 'gt'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/williams/MYFPGA/FPGA Training Data Etri_fso/sfp_int/sfp_int_0/gt_ex/gt_ex.srcs/sources_1/ip/gt/gt.xci
# IP: The module: 'gt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/williams/MYFPGA/FPGA Training Data Etri_fso/sfp_int/sfp_int_0/gt_ex/gt_ex.gen/sources_1/ip/gt/synth/gt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gt'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/williams/MYFPGA/FPGA Training Data Etri_fso/sfp_int/sfp_int_0/gt_ex/gt_ex.gen/sources_1/ip/gt/synth/gt.xdc
# XDC: The top module name and the constraint reference have the same name: 'gt'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
