# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/ip/delay_combiner/delay_combiner.xci
# IP: The module: 'delay_combiner' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/delay_combiner/delay_combiner.xdc
# XDC: The top module name and the constraint reference have the same name: 'delay_combiner'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/delay_combiner/delay_combiner_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'delay_combiner'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/ip/delay_combiner/delay_combiner.xci
# IP: The module: 'delay_combiner' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/delay_combiner/delay_combiner.xdc
# XDC: The top module name and the constraint reference have the same name: 'delay_combiner'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/delay_combiner/delay_combiner_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'delay_combiner'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
