# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/williams/MYFPGA/FSO FPGA/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/ip/cross_logic_gth_head/cross_logic_gth_head.xci
# IP: The module: 'cross_logic_gth_head' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/williams/MYFPGA/FSO FPGA/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/cross_logic_gth_head/cross_logic_gth_head.xdc
# XDC: The top module name and the constraint reference have the same name: 'cross_logic_gth_head'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/williams/MYFPGA/FSO FPGA/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/cross_logic_gth_head/cross_logic_gth_head_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'cross_logic_gth_head'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/williams/MYFPGA/FSO FPGA/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/cross_logic_gth_head/cross_logic_gth_head_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cross_logic_gth_head'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/williams/MYFPGA/FSO FPGA/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/ip/cross_logic_gth_head/cross_logic_gth_head.xci
# IP: The module: 'cross_logic_gth_head' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/williams/MYFPGA/FSO FPGA/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/cross_logic_gth_head/cross_logic_gth_head.xdc
# XDC: The top module name and the constraint reference have the same name: 'cross_logic_gth_head'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/williams/MYFPGA/FSO FPGA/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/cross_logic_gth_head/cross_logic_gth_head_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'cross_logic_gth_head'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/williams/MYFPGA/FSO FPGA/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/cross_logic_gth_head/cross_logic_gth_head_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cross_logic_gth_head'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
