# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/yrzal0/_FPGA/12_ethernet_test/src/ip/icmp_rx_ram_8_256/icmp_rx_ram_8_256.xci
# IP: The module: 'icmp_rx_ram_8_256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yrzal0/_FPGA/12_ethernet_test/src/ip/icmp_rx_ram_8_256/icmp_rx_ram_8_256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'icmp_rx_ram_8_256'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/yrzal0/_FPGA/12_ethernet_test/src/ip/icmp_rx_ram_8_256/icmp_rx_ram_8_256.xci
# IP: The module: 'icmp_rx_ram_8_256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yrzal0/_FPGA/12_ethernet_test/src/ip/icmp_rx_ram_8_256/icmp_rx_ram_8_256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'icmp_rx_ram_8_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
