# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/yrzal0/_FPGA/12_ethernet_test/src/ip/eth_data_fifo/eth_data_fifo.xci
# IP: The module: 'eth_data_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yrzal0/_FPGA/12_ethernet_test/src/ip/eth_data_fifo/eth_data_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_data_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/yrzal0/_FPGA/12_ethernet_test/src/ip/eth_data_fifo/eth_data_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/yrzal0/_FPGA/12_ethernet_test/src/ip/eth_data_fifo/eth_data_fifo.xci
# IP: The module: 'eth_data_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yrzal0/_FPGA/12_ethernet_test/src/ip/eth_data_fifo/eth_data_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/yrzal0/_FPGA/12_ethernet_test/src/ip/eth_data_fifo/eth_data_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
