# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/ax/ku042/12_ethernet_test/src/ethernet.xdc

# IP: E:/ax/ku042/12_ethernet_test/src/ip/icmp_rx_ram_8_256/icmp_rx_ram_8_256.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==icmp_rx_ram_8_256 || ORIG_REF_NAME==icmp_rx_ram_8_256} -quiet] -quiet

# IP: E:/ax/ku042/12_ethernet_test/src/ip/udp_rx_ram_8_2048/udp_rx_ram_8_2048.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==udp_rx_ram_8_2048 || ORIG_REF_NAME==udp_rx_ram_8_2048} -quiet] -quiet

# IP: E:/ax/ku042/12_ethernet_test/src/ip/udp_checksum_fifo/udp_checksum_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==udp_checksum_fifo || ORIG_REF_NAME==udp_checksum_fifo} -quiet] -quiet

# IP: E:/ax/ku042/12_ethernet_test/src/ip/udp_tx_data_fifo/udp_tx_data_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==udp_tx_data_fifo || ORIG_REF_NAME==udp_tx_data_fifo} -quiet] -quiet

# IP: E:/ax/ku042/12_ethernet_test/src/ip/len_fifo/len_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==len_fifo || ORIG_REF_NAME==len_fifo} -quiet] -quiet

# IP: E:/ax/ku042/12_ethernet_test/src/ip/eth_data_fifo/eth_data_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth_data_fifo || ORIG_REF_NAME==eth_data_fifo} -quiet] -quiet

# IP: E:/ax/ku042/12_ethernet_test/src/ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
