# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcku040-ffva1156-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/ax/ku042/12_ethernet_test/12_ethernet_test.cache/wt [current_project]
set_property parent.project_path E:/ax/ku042/12_ethernet_test/12_ethernet_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/ax/ku042/12_ethernet_test/12_ethernet_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/ax/ku042/12_ethernet_test/src/new/eth_src/mac/arp_cache.v
  E:/ax/ku042/12_ethernet_test/src/new/eth_src/mac/rx/arp_rx.v
  E:/ax/ku042/12_ethernet_test/src/new/eth_src/mac/tx/arp_tx.v
  E:/ax/ku042/12_ethernet_test/src/new/eth_src/mac/crc.v
  E:/ax/ku042/12_ethernet_test/src/new/eth_src/ethernet_test.v
  E:/ax/ku042/12_ethernet_test/src/new/eth_src/arbi/gmii_arbi.v
  E:/ax/ku042/12_ethernet_test/src/new/eth_src/arbi/gmii_rx_buffer.v
  E:/ax/ku042/12_ethernet_test/src/new/eth_src/arbi/gmii_tx_buffer.v
  E:/ax/ku042/12_ethernet_test/src/new/eth_src/mac/icmp_reply.v
  E:/ax/ku042/12_ethernet_test/src/new/eth_src/mac/rx/ip_rx.v
  E:/ax/ku042/12_ethernet_test/src/new/eth_src/mac/tx/ip_tx.v
  E:/ax/ku042/12_ethernet_test/src/new/eth_src/mac/tx/ip_tx_mode.v
  E:/ax/ku042/12_ethernet_test/src/new/eth_src/mac/rx/mac_rx.v
  E:/ax/ku042/12_ethernet_test/src/new/eth_src/mac/rx/mac_rx_top.v
  E:/ax/ku042/12_ethernet_test/src/new/eth_src/mac/mac_test.v
  E:/ax/ku042/12_ethernet_test/src/new/eth_src/mac/mac_top.v
  E:/ax/ku042/12_ethernet_test/src/new/eth_src/mac/tx/mac_tx.v
  E:/ax/ku042/12_ethernet_test/src/new/eth_src/mac/tx/mac_tx_mode.v
  E:/ax/ku042/12_ethernet_test/src/new/eth_src/mac/tx/mac_tx_top.v
  E:/ax/ku042/12_ethernet_test/src/new/eth_src/mdio/smi_config.v
  E:/ax/ku042/12_ethernet_test/src/new/eth_src/mdio/smi_read_write.v
  E:/ax/ku042/12_ethernet_test/src/new/eth_src/mac/rx/udp_rx.v
  E:/ax/ku042/12_ethernet_test/src/new/eth_src/mac/tx/udp_tx.v
  E:/ax/ku042/12_ethernet_test/src/new/eth_src/util_gmii_to_rgmii.v
  E:/ax/ku042/12_ethernet_test/src/new/top.v
}
read_ip -quiet E:/ax/ku042/12_ethernet_test/src/ip/icmp_rx_ram_8_256/icmp_rx_ram_8_256.xci
set_property used_in_implementation false [get_files -all e:/ax/ku042/12_ethernet_test/src/ip/icmp_rx_ram_8_256/icmp_rx_ram_8_256_ooc.xdc]

read_ip -quiet E:/ax/ku042/12_ethernet_test/src/ip/udp_rx_ram_8_2048/udp_rx_ram_8_2048.xci
set_property used_in_implementation false [get_files -all e:/ax/ku042/12_ethernet_test/src/ip/udp_rx_ram_8_2048/udp_rx_ram_8_2048_ooc.xdc]

read_ip -quiet E:/ax/ku042/12_ethernet_test/src/ip/udp_checksum_fifo/udp_checksum_fifo.xci
set_property used_in_implementation false [get_files -all e:/ax/ku042/12_ethernet_test/src/ip/udp_checksum_fifo/udp_checksum_fifo.xdc]
set_property used_in_implementation false [get_files -all e:/ax/ku042/12_ethernet_test/src/ip/udp_checksum_fifo/udp_checksum_fifo_ooc.xdc]

read_ip -quiet E:/ax/ku042/12_ethernet_test/src/ip/udp_tx_data_fifo/udp_tx_data_fifo.xci
set_property used_in_implementation false [get_files -all e:/ax/ku042/12_ethernet_test/src/ip/udp_tx_data_fifo/udp_tx_data_fifo.xdc]
set_property used_in_implementation false [get_files -all e:/ax/ku042/12_ethernet_test/src/ip/udp_tx_data_fifo/udp_tx_data_fifo_ooc.xdc]

read_ip -quiet E:/ax/ku042/12_ethernet_test/src/ip/len_fifo/len_fifo.xci
set_property used_in_implementation false [get_files -all e:/ax/ku042/12_ethernet_test/src/ip/len_fifo/len_fifo.xdc]
set_property used_in_implementation false [get_files -all e:/ax/ku042/12_ethernet_test/src/ip/len_fifo/len_fifo_ooc.xdc]

read_ip -quiet E:/ax/ku042/12_ethernet_test/src/ip/eth_data_fifo/eth_data_fifo.xci
set_property used_in_implementation false [get_files -all e:/ax/ku042/12_ethernet_test/src/ip/eth_data_fifo/eth_data_fifo.xdc]
set_property used_in_implementation false [get_files -all e:/ax/ku042/12_ethernet_test/src/ip/eth_data_fifo/eth_data_fifo_ooc.xdc]

read_ip -quiet E:/ax/ku042/12_ethernet_test/src/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/ax/ku042/12_ethernet_test/src/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/ax/ku042/12_ethernet_test/src/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/ax/ku042/12_ethernet_test/src/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/ax/ku042/12_ethernet_test/src/ethernet.xdc
set_property used_in_implementation false [get_files E:/ax/ku042/12_ethernet_test/src/ethernet.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top -part xcku040-ffva1156-2-i


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
