# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/ip/serdes_framer/serdes_framer.xci
# IP: The module: 'serdes_framer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/serdes_framer/serdes_framer.xdc
# XDC: The top module name and the constraint reference have the same name: 'serdes_framer'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/serdes_framer/serdes_framer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'serdes_framer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/ip/serdes_framer/serdes_framer.xci
# IP: The module: 'serdes_framer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/serdes_framer/serdes_framer.xdc
# XDC: The top module name and the constraint reference have the same name: 'serdes_framer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/serdes_framer/serdes_framer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'serdes_framer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
