# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/File xdc/sda_top.xdc

# IP: ip/serdes_assembler/serdes_assembler.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==serdes_assembler || ORIG_REF_NAME==serdes_assembler} -quiet] -quiet

# IP: ip/cross_logic_gth_load/cross_logic_gth_load.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cross_logic_gth_load || ORIG_REF_NAME==cross_logic_gth_load} -quiet] -quiet

# IP: ip/bram_rs/bram_rs.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_rs || ORIG_REF_NAME==bram_rs} -quiet] -quiet

# IP: ip/cross_gth_logic/cross_gth_logic.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cross_gth_logic || ORIG_REF_NAME==cross_gth_logic} -quiet] -quiet

# IP: ip/cross_logic_gth/cross_logic_gth.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cross_logic_gth || ORIG_REF_NAME==cross_logic_gth} -quiet] -quiet

# IP: ip/delay_combiner/delay_combiner.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==delay_combiner || ORIG_REF_NAME==delay_combiner} -quiet] -quiet

# IP: ip/cross_gth_logic_load/cross_gth_logic_load.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cross_gth_logic_load || ORIG_REF_NAME==cross_gth_logic_load} -quiet] -quiet

# IP: ip/serdes_framer/serdes_framer.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==serdes_framer || ORIG_REF_NAME==serdes_framer} -quiet] -quiet

# IP: ip/clk_wiz_1/clk_wiz_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_1 || ORIG_REF_NAME==clk_wiz_1} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
