# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param tcl.statsThreshold 360
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcku060-ffva1156-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.cache/wt} [current_project]
set_property parent.project_path {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/decoder/assembler.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/decoder/assembler_top.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/autorun.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/rs_codec/chien_search.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/encoder/combiner.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/decoder/core_rx.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/encoder/core_tx.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/encoder/crc_16.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/encoder/crc_32.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/decoder/decoder_top.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/encoder/encoder_top.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/error_inject.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/rs_codec/euclid_proc.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/rs_codec/forney_math.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/encoder/framer.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/encoder/framer_top.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/rs_codec/inverter.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/encoder/lpc.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/decoder/lpc_dec.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/decoder/lpc_dec_top.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/encoder/lpc_top.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/rs_codec/multiplier.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/rs_codec/rs_decoder.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/decoder/rs_decoder_64.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/rs_codec/rs_encoder.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/encoder/rs_encoder_64.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/decoder/rx_gth_logic.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/decoder/rx_logic_gth.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/encoder/scrambler.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/decoder/separator.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/stream_input.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/rs_codec/syndrome_unit.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/encoder/x_gth_logic.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/encoder/x_logic_gth.v}
  {/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/imports/Source core file/top.v}
}
read_ip -quiet {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci}}
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc}}]

read_ip -quiet {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci}}
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc}}]

read_ip -quiet {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/ip/cross_gth_logic/cross_gth_logic.xci}}
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/cross_gth_logic/cross_gth_logic.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/cross_gth_logic/cross_gth_logic_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/cross_gth_logic/cross_gth_logic_ooc.xdc}}]

read_ip -quiet {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/ip/cross_gth_logic_head/cross_gth_logic_head.xci}}
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/cross_gth_logic_head/cross_gth_logic_head.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/cross_gth_logic_head/cross_gth_logic_head_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/cross_gth_logic_head/cross_gth_logic_head_ooc.xdc}}]

read_ip -quiet {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/ip/cross_gth_logic_load/cross_gth_logic_load.xci}}
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/cross_gth_logic_load/cross_gth_logic_load.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/cross_gth_logic_load/cross_gth_logic_load_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/cross_gth_logic_load/cross_gth_logic_load_ooc.xdc}}]

read_ip -quiet {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/ip/cross_logic_gth/cross_logic_gth.xci}}
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/cross_logic_gth/cross_logic_gth.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/cross_logic_gth/cross_logic_gth_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/cross_logic_gth/cross_logic_gth_ooc.xdc}}]

read_ip -quiet {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/ip/cross_logic_gth_head/cross_logic_gth_head.xci}}
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/cross_logic_gth_head/cross_logic_gth_head.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/cross_logic_gth_head/cross_logic_gth_head_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/cross_logic_gth_head/cross_logic_gth_head_ooc.xdc}}]

read_ip -quiet {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/ip/cross_logic_gth_load/cross_logic_gth_load.xci}}
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/cross_logic_gth_load/cross_logic_gth_load.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/cross_logic_gth_load/cross_logic_gth_load_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/cross_logic_gth_load/cross_logic_gth_load_ooc.xdc}}]

read_ip -quiet {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/ip/delay_combiner/delay_combiner.xci}}
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/delay_combiner/delay_combiner.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/delay_combiner/delay_combiner_ooc.xdc}}]

read_ip -quiet {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/ip/delay_rs/delay_rs.xci}}
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/delay_rs/delay_rs.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/delay_rs/delay_rs_ooc.xdc}}]

read_ip -quiet {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/ip/serdes_assembler/serdes_assembler.xci}}
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/serdes_assembler/serdes_assembler.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/serdes_assembler/serdes_assembler_ooc.xdc}}]

read_ip -quiet {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/sources_1/ip/serdes_framer/serdes_framer.xci}}
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/serdes_framer/serdes_framer.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.gen/sources_1/ip/serdes_framer/serdes_framer_ooc.xdc}}]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/constrs_1/imports/File xdc/sda_top.xdc}}
set_property used_in_implementation false [get_files {{/home/williams/MYFPGA/FPGA Final/sda_codec_clean/sda_codec_clean/sda_codec_clean.srcs/constrs_1/imports/File xdc/sda_top.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xcku060-ffva1156-2-i
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
