# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/williams/MYFPGA/FPGA Final/sfp_int/sfp_int_0/gt_ex/gt_ex.srcs/sources_1/ip/cross_logic_gth/cross_logic_gth.xci
# IP: The module: 'cross_logic_gth' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/williams/MYFPGA/FPGA Final/sfp_int/sfp_int_0/gt_ex/sda_codec_0.gen/sources_1/ip/cross_logic_gth/cross_logic_gth.xdc
# XDC: The top module name and the constraint reference have the same name: 'cross_logic_gth'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/williams/MYFPGA/FPGA Final/sfp_int/sfp_int_0/gt_ex/sda_codec_0.gen/sources_1/ip/cross_logic_gth/cross_logic_gth_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'cross_logic_gth'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/williams/MYFPGA/FPGA Final/sfp_int/sfp_int_0/gt_ex/sda_codec_0.gen/sources_1/ip/cross_logic_gth/cross_logic_gth_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cross_logic_gth'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/williams/MYFPGA/FPGA Final/sfp_int/sfp_int_0/gt_ex/gt_ex.srcs/sources_1/ip/cross_logic_gth/cross_logic_gth.xci
# IP: The module: 'cross_logic_gth' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/williams/MYFPGA/FPGA Final/sfp_int/sfp_int_0/gt_ex/sda_codec_0.gen/sources_1/ip/cross_logic_gth/cross_logic_gth.xdc
# XDC: The top module name and the constraint reference have the same name: 'cross_logic_gth'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/williams/MYFPGA/FPGA Final/sfp_int/sfp_int_0/gt_ex/sda_codec_0.gen/sources_1/ip/cross_logic_gth/cross_logic_gth_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'cross_logic_gth'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/williams/MYFPGA/FPGA Final/sfp_int/sfp_int_0/gt_ex/sda_codec_0.gen/sources_1/ip/cross_logic_gth/cross_logic_gth_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cross_logic_gth'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
