
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 8 [current_design]
set_property CONFIG_MODE SPIx8 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]

create_clock -period 5.000 -name sys_clk_in_p -waveform {0.000 2.500} [get_ports sys_clk_p]

set_property PACKAGE_PIN AK11 [get_ports fan]
set_property PACKAGE_PIN AK17 [get_ports sys_clk_p]

set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports sys_clk_p]
set_property IOSTANDARD LVCMOS18 [get_ports fan]




set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[27]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[17]}]
set_property MARK_DEBUG false [get_nets {sl_oport0_i_0[11]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[35]}]
set_property MARK_DEBUG false [get_nets {sl_oport0_i_0[6]}]
set_property MARK_DEBUG false [get_nets <const0>]
set_property MARK_DEBUG false [get_nets fan]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[28]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[24]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[23]}]
set_property MARK_DEBUG false [get_nets {sl_oport0_i_0[15]}]
set_property MARK_DEBUG false [get_nets {sl_oport0_i_0[9]}]
set_property MARK_DEBUG false [get_nets sys_clk_in]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[12]}]
set_property MARK_DEBUG false [get_nets {stream_data[1]}]
set_property MARK_DEBUG false [get_nets {fso_data[7]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[33]}]
set_property MARK_DEBUG false [get_nets {stream_data[5]}]
set_property MARK_DEBUG false [get_nets {data_out[3]}]
set_property MARK_DEBUG false [get_nets {data_out[2]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[20]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[34]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[36]}]
set_property MARK_DEBUG false [get_nets {fso_data[3]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[16]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[13]}]
set_property MARK_DEBUG false [get_nets {sl_oport0_i_0[5]}]
set_property MARK_DEBUG false [get_nets fso_dv]
set_property MARK_DEBUG false [get_nets {stream_data[3]}]
set_property MARK_DEBUG false [get_nets {sl_oport0_i_0[1]}]
set_property MARK_DEBUG false [get_nets {sl_oport0_i_0[16]}]
set_property MARK_DEBUG false [get_nets {fso_data[4]}]
set_property MARK_DEBUG false [get_nets {sl_oport0_i_0[12]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[19]}]
set_property MARK_DEBUG false [get_nets {sl_oport0_i_0[7]}]
set_property MARK_DEBUG false [get_nets {stream_data[2]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[11]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[9]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[3]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[8]}]
set_property MARK_DEBUG false [get_nets encoder_dv]
set_property MARK_DEBUG false [get_nets {sl_oport0_i_0[0]}]
set_property MARK_DEBUG false [get_nets {fso_data[6]}]
set_property MARK_DEBUG false [get_nets {encoder_data[7]}]
set_property MARK_DEBUG false [get_nets {data_out[0]}]
set_property MARK_DEBUG false [get_nets valid]
set_property MARK_DEBUG false [get_nets {encoder_data[1]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[21]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[7]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[29]}]
set_property MARK_DEBUG false [get_nets {encoder_data[6]}]
set_property MARK_DEBUG false [get_nets {sl_oport0_i_0[13]}]
set_property MARK_DEBUG false [get_nets {encoder_data[5]}]
set_property MARK_DEBUG false [get_nets sys_clk_n]
set_property MARK_DEBUG false [get_nets en]
set_property MARK_DEBUG false [get_nets {encoder_data[0]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[32]}]
set_property MARK_DEBUG false [get_nets {sl_oport0_i_0[10]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[30]}]
set_property MARK_DEBUG false [get_nets {sl_oport0_i_0[8]}]
set_property MARK_DEBUG false [get_nets {sl_oport0_i_0[2]}]
set_property MARK_DEBUG false [get_nets {data_out[5]}]
set_property MARK_DEBUG false [get_nets {fso_data[2]}]
set_property MARK_DEBUG false [get_nets sys_clk_p]
set_property MARK_DEBUG false [get_nets {stream_data[6]}]
set_property MARK_DEBUG false [get_nets {sl_oport0_i_0[14]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[5]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[4]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[1]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[6]}]
set_property MARK_DEBUG false [get_nets {data_out[7]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[26]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[14]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[22]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[18]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[25]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[15]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[31]}]
set_property MARK_DEBUG false [get_nets {sl_oport0_i_0[3]}]
set_property MARK_DEBUG false [get_nets {encoder_data[2]}]
set_property MARK_DEBUG false [get_nets {sl_oport0_i_0[4]}]
set_property MARK_DEBUG false [get_nets {fso_data[5]}]
set_property MARK_DEBUG false [get_nets <const1>]
set_property MARK_DEBUG false [get_nets {encoder_data[4]}]
set_property MARK_DEBUG false [get_nets {stream_data[0]}]
set_property MARK_DEBUG false [get_nets sys_clk]
set_property MARK_DEBUG false [get_nets {encoder_data[3]}]
set_property MARK_DEBUG false [get_nets {stream_data[4]}]
set_property MARK_DEBUG false [get_nets {data_out[4]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[2]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[10]}]
set_property MARK_DEBUG false [get_nets {sl_iport0_o_0[0]}]
set_property MARK_DEBUG false [get_nets {fso_data[0]}]
set_property MARK_DEBUG false [get_nets {stream_data[7]}]
set_property MARK_DEBUG false [get_nets {data_out[6]}]
set_property MARK_DEBUG false [get_nets {data_out[1]}]
set_property MARK_DEBUG false [get_nets {fso_data[1]}]
set_property MARK_DEBUG false [get_nets stream_dv]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_wiz_inst/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {fso_data[0]} {fso_data[1]} {fso_data[2]} {fso_data[3]} {fso_data[4]} {fso_data[5]} {fso_data[6]} {fso_data[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {encoder_data[0]} {encoder_data[1]} {encoder_data[2]} {encoder_data[3]} {encoder_data[4]} {encoder_data[5]} {encoder_data[6]} {encoder_data[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {data_out[0]} {data_out[1]} {data_out[2]} {data_out[3]} {data_out[4]} {data_out[5]} {data_out[6]} {data_out[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {stream_data[0]} {stream_data[1]} {stream_data[2]} {stream_data[3]} {stream_data[4]} {stream_data[5]} {stream_data[6]} {stream_data[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list encoder_dv]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list fso_dv]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list stream_dv]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list valid]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets sys_clk]
