# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/yrzal0/_FPGA/12_ethernet_test/src/ip/udp_rx_ram_8_2048/udp_rx_ram_8_2048.xci
# IP: The module: 'udp_rx_ram_8_2048' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yrzal0/_FPGA/12_ethernet_test/src/ip/udp_rx_ram_8_2048/udp_rx_ram_8_2048_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'udp_rx_ram_8_2048'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/yrzal0/_FPGA/12_ethernet_test/src/ip/udp_rx_ram_8_2048/udp_rx_ram_8_2048.xci
# IP: The module: 'udp_rx_ram_8_2048' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yrzal0/_FPGA/12_ethernet_test/src/ip/udp_rx_ram_8_2048/udp_rx_ram_8_2048_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'udp_rx_ram_8_2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
